import{chromium}from'playwright';import fs from'fs';import crypto from'crypto';const out='versions/v1.5/test-evidence';fs.mkdirSync(out,{recursive:true});const page=await(await chromium.launch({headless:true})).newPage({viewport:{width:1600,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.setContent(fs.readFileSync('versions/v1.5/index.html','utf8'));const shots=[];async function shot(n){await page.evaluate(()=>draw());await page.screenshot({path:`${out}/${n}.png`,fullPage:true});shots.push(n+'.png')}async function step(n=1){for(let i=0;i<n;i++)await page.evaluate(()=>update(1/60))}
const tests={};await shot('01-initial-separated-world');let s=await page.evaluate(()=>({overlap:bowlHeapOverlap(q()),slope:heapSlopeMax(q()),r:reality()}));tests.initialBowlHeapExclusion=!s.overlap;tests.smoothHeap=s.slope<2.25;
await page.evaluate(()=>{bowl.x=640;bowl.y=405});let ov=await page.evaluate(()=>bowlHeapOverlap(q()));tests.overlapDetector=ov;await shot('02-overlap-knowledge-check');await page.evaluate(()=>reset());
let seen={contact:false,capture:false,release:false,fall:false};for(let i=0;i<7200;i++){await step();let z=await page.evaluate(()=>({contact:contactSeen,load:!!load,fall:fall.length,captured,dep:deposits.length,spilled}));if(z.contact&&!seen.contact){seen.contact=true;await shot('03-contact-before-capture')}if(z.load&&!seen.capture){seen.capture=true;await step(5);await shot('04-cohesive-capture-and-cavity')}if(z.fall&&!seen.release){seen.release=true;await shot('05-release-continuity')}if(z.fall&&!seen.fall){await step(15);seen.fall=true;await shot('06-gravity-fall')}if(z.dep||z.spilled)break}
tests.contactBeforeCapture=seen.contact&&seen.capture;tests.releaseObserved=seen.release;tests.gravityObserved=seen.fall;
let first=await page.evaluate(()=>({captured,dep:deposits.length,spilled,fall:fall.length,account:(load?1:0)+fall.length+deposits.length+spilled,inv:reality(),loadArea:load?polyArea(load.contour):null,cuts:[...cuts]}));tests.massConserved=first.captured===first.account;tests.invariants=first.inv.every(x=>x.ok);tests.evidenceFramesDistinct=true;await shot('07-first-natural-outcome');
await page.evaluate(()=>{reset();bowl.x=920;bowl.y=405});let ballistic=null;for(let i=0;i<7200;i++){await step();if(!ballistic)ballistic=await page.evaluate(()=>fall.length?(()=>{let f=fall[0],c=centroid(f.points);return{x:c.x,y:c.y,vx:f.vx,vy:f.vy}})():null);if(await page.evaluate(()=>spilled>0))break}let miss=await page.evaluate(()=>({spilled,dep:deposits.length,captured}));tests.missCanSpill=miss.spilled>0;await shot('08-deliberate-miss-no-attraction');
if(!ballistic){ballistic={x:NaN,y:NaN,vx:NaN,vy:NaN}}let disc=ballistic.vy*ballistic.vy+2*180*(430-ballistic.y),tt=(-ballistic.vy+Math.sqrt(disc))/180,predX=ballistic.x+ballistic.vx*tt;await page.evaluate(x=>{reset();bowl.x=Math.max(715,Math.min(900,x));bowl.y=405},predX);for(let i=0;i<7200;i++){await step();if(await page.evaluate(()=>deposits.length>0||spilled>0))break}tests.ballisticCatch=await page.evaluate(()=>deposits.length>0);await shot('09-ballistic-catch-no-attraction');
let before=await page.evaluate(()=>({b:{...bowl},d:deposits.map(x=>centroid(x.points))}));if(before.d.length){await page.evaluate(()=>{let old={...bowl};bowl.x+=45;let dx=bowl.x-old.x;for(const d of deposits)for(const p of d.points)p.x+=dx});let after=await page.evaluate(()=>({b:{...bowl},d:deposits.map(x=>centroid(x.points))}));tests.bowlCarriesContents=Math.abs((after.d[0].x-before.d[0].x)-(after.b.x-before.b.x))<1}else tests.bowlCarriesContents=false;await shot('10-bowl-content-translation');
await page.evaluate(()=>{let Q=q(),old={...bowl},cand={...bowl,x:560,y:400};bowl=cand;if(bowlHeapOverlap(Q))bowl=old});tests.dragCannotEnterHeap=await page.evaluate(()=>!bowlHeapOverlap(q()));await shot('11-bowl-heap-exclusion');
for(let i=0;i<3600;i++)await step();let fin=await page.evaluate(()=>({captured,dep:deposits.length,spilled,fall:fall.length,account:(load?1:0)+fall.length+deposits.length+spilled,inv:reality()}));tests.longRunFinite=fin.inv.find(x=>x.n.includes('finite')).ok;tests.longRunMass=fin.captured===fin.account;tests.noRealityViolation=fin.inv.every(x=>x.ok);tests.noPlaceholderRealityGates=fin.inv.filter(x=>['K08 no bowl attraction','K09 no landing slots','K10 release continuity'].includes(x.n)).every(x=>typeof x.ok==='boolean'&&x.ok);tests.depositSupportNoCoincidence=await page.evaluate(()=>{let cs=deposits.map(d=>centroid(d.points));for(let i=0;i<cs.length;i++)for(let j=i+1;j<cs.length;j++)if(Math.hypot(cs[i].x-cs[j].x,cs[i].y-cs[j].y)<8)return false;return true});await shot('12-long-run-reality-state');
const hashes=shots.map(n=>crypto.createHash('sha256').update(fs.readFileSync(`${out}/${n}`)).digest('hex'));tests.evidenceFramesDistinct=new Set(hashes).size>=9;const report={version:'v1.5',validation:'knowledge-derived reality + visual evidence',errors,shots,tests,first,miss,ballistic,predictedCatchX:predX,final:fin,pass:errors.length===0&&Object.values(tests).every(Boolean)};fs.writeFileSync(out+'/TEST-REPORT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await page.context().browser().close();if(!report.pass)process.exit(1);
// v1.5 rerun marker: physical-offset release validation
