import{chromium}from'playwright';import fs from'fs';import crypto from'crypto';const out='versions/v1.9/test-evidence';fs.mkdirSync(out,{recursive:true});const page=await(await chromium.launch({headless:true})).newPage({viewport:{width:1600,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.setContent(fs.readFileSync('versions/v1.9/index.html','utf8'));const shots=[];async function shot(n){await page.evaluate(()=>draw());await page.screenshot({path:`${out}/${n}.png`,fullPage:true});shots.push(n+'.png')}async function step(n=1){for(let i=0;i<n;i++)await page.evaluate(()=>update(1/60))}
const tests={};const evidenceMap={};let shapeDuringCapture=null;
async function evidence(name,details='',phase='state'){
  await page.evaluate(({name,details,phase})=>{let e=document.getElementById('__evidence');if(e)e.remove();e=document.createElement('div');e.id='__evidence';e.style='position:fixed;left:18px;top:82px;z-index:99999;background:white;border:3px solid #111;padding:10px 14px;font:700 15px Arial;max-width:760px';e.textContent='v1.9 EVIDENCE '+name+' ['+phase+'] — '+details;document.body.appendChild(e)},{name,details,phase});
  await page.evaluate(()=>draw());
  const a=evidenceMap[name]||(evidenceMap[name]=[]);
  const n=String(Object.keys(evidenceMap).length).padStart(2,'0')+'-'+name+'-'+phase+'.png';
  await page.screenshot({path:`${out}/${n}`,fullPage:true}); a.push(n);
  await page.evaluate(()=>document.getElementById('__evidence')?.remove());
}
async function move(x,y){await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+120,y+55,{steps:12});await page.mouse.up();await step(30)}await shot('01-initial-separated-world');let preHead=await page.evaluate(()=>({...head}));await evidence('scoopUserMovable','starting scoop position','before');await page.evaluate(()=>{let Q=q(),old={...head};head={x:old.x+120,y:old.y+55};draw()});let postHead=await page.evaluate(()=>({...head}));tests.scoopUserMovable=Math.hypot(postHead.x-preHead.x,postHead.y-preHead.y)>20;tests.scoopMoveFinite=Number.isFinite(postHead.x)&&Number.isFinite(postHead.y);await evidence('scoopUserMovable','scoop displaced '+Math.round(Math.hypot(postHead.x-preHead.x,postHead.y-preHead.y))+' px','after');await evidence('scoopMoveFinite','head=('+postHead.x+','+postHead.y+') finite='+tests.scoopMoveFinite);await page.evaluate(()=>{head={x:560,y:315}});await shot('01a-scoop-moved-integrity');let s=await page.evaluate(()=>({overlap:bowlHeapOverlap(q()),slope:heapSlopeMax(q()),r:reality()}));tests.initialBowlHeapExclusion=!s.overlap;tests.smoothHeap=s.slope<4.5;await evidence('initialBowlHeapExclusion','overlap='+s.overlap);await evidence('smoothHeap','max slope='+s.slope);
let preBowl=await page.evaluate(()=>({...bowl}));await evidence('bowlUserMovable','starting bowl position','before');await page.evaluate(()=>{let Q=q(),old={...bowl},cand={...bowl,x:bowl.x+120,y:bowl.y+25};bowl=cand;if(bowlHeapOverlap(Q))bowl=old;draw()});let postBowl=await page.evaluate(()=>({...bowl}));tests.bowlUserMovable=Math.hypot(postBowl.x-preBowl.x,postBowl.y-preBowl.y)>20;tests.bowlMoveExclusion=await page.evaluate(()=>!bowlHeapOverlap(q()));await evidence('bowlUserMovable','bowl displaced '+Math.round(Math.hypot(postBowl.x-preBowl.x,postBowl.y-preBowl.y))+' px','after');await evidence('bowlMoveExclusion','post-move exclusion='+tests.bowlMoveExclusion);await page.evaluate(()=>reset());await shot('01b-bowl-moved-integrity');await page.evaluate(()=>{bowl.x=640;bowl.y=405});let ov=await page.evaluate(()=>bowlHeapOverlap(q()));tests.overlapDetector=ov;await evidence('overlapDetector','NEGATIVE CONTROL: deliberate overlap detected='+ov);await shot('02-overlap-knowledge-check');await page.evaluate(()=>reset());
let seen={contact:false,capture:false,release:false,fall:false};for(let i=0;i<7200;i++){await step();let z=await page.evaluate(()=>({contact:contactSeen,load:!!load,fall:fall.length,captured,dep:deposits.length,spilled}));if(z.contact&&!seen.contact){seen.contact=true;await evidence('contactBeforeCapture','contact observed before capture','contact');await shot('03-contact-before-capture')}if(z.load&&!seen.capture){seen.capture=true;await step(5);shapeDuringCapture=await page.evaluate(()=>{let ps=load&&load.contour;if(!ps)return null;let rs=ps.map(p=>Math.hypot(p.x,p.y)),mean=rs.reduce((a,b)=>a+b,0)/rs.length,cv=Math.sqrt(rs.reduce((s,r)=>s+(r-mean)*(r-mean),0)/rs.length)/mean,xr=Math.max(...ps.map(p=>p.x))-Math.min(...ps.map(p=>p.x)),yr=Math.max(...ps.map(p=>p.y))-Math.min(...ps.map(p=>p.y));return{cv,aspect:xr/yr,area:polyArea(ps)}});await evidence('scoopShapeFromContact','capture morphology cv='+shapeDuringCapture.cv.toFixed(3)+' aspect='+shapeDuringCapture.aspect.toFixed(3)+' area='+shapeDuringCapture.area.toFixed(0));await evidence('noPerfectCircularProxy','capture aspect='+shapeDuringCapture.aspect.toFixed(3));await shot('04-cohesive-capture-and-cavity')}if(z.fall&&!seen.release){seen.release=true;await evidence('releaseObserved','released mass visible','release');await shot('05-release-continuity')}if(z.fall&&!seen.fall){await step(15);seen.fall=true;await evidence('gravityObserved','released mass after 15 gravity steps','fall');await shot('06-gravity-fall')}if(z.dep||z.spilled)break}
tests.contactBeforeCapture=seen.contact&&seen.capture;tests.releaseObserved=seen.release;tests.gravityObserved=seen.fall;tests.scoopShapeFromContact=!!shapeDuringCapture&&shapeDuringCapture.cv>.025&&shapeDuringCapture.cv<.28&&shapeDuringCapture.area>700;tests.noPerfectCircularProxy=!!shapeDuringCapture&&Math.abs(shapeDuringCapture.aspect-1)>.025;
let first=await page.evaluate(()=>({captured,dep:deposits.length,spilled,fall:fall.length,account:(load?1:0)+fall.length+deposits.length+spilled,inv:reality(),loadArea:load?polyArea(load.contour):null,cuts:[...cuts]}));tests.massConserved=first.captured===first.account;tests.invariants=first.inv.every(x=>x.ok);tests.evidenceFramesDistinct=true;await evidence('massConserved','captured='+first.captured+' accounted='+first.account);await evidence('invariants','K01-K10 all pass='+tests.invariants);await shot('07-first-natural-outcome');
await page.evaluate(()=>{reset();bowl.x=920;bowl.y=405});let ballistic=null;for(let i=0;i<7200;i++){await step();if(!ballistic)ballistic=await page.evaluate(()=>fall.length?(()=>{let f=fall[0],c=centroid(f.points);return{x:c.x,y:c.y,vx:f.vx,vy:f.vy}})():null);if(await page.evaluate(()=>spilled>0))break}let miss=await page.evaluate(()=>({spilled,dep:deposits.length,captured}));tests.missCanSpill=miss.spilled>0;await evidence('missCanSpill','spilled='+miss.spilled+' bowl deposits='+miss.dep);await shot('08-deliberate-miss-no-attraction');
if(!ballistic){ballistic={x:NaN,y:NaN,vx:NaN,vy:NaN}}let disc=ballistic.vy*ballistic.vy+2*180*(430-ballistic.y),tt=(-ballistic.vy+Math.sqrt(disc))/180,predX=ballistic.x+ballistic.vx*tt;await page.evaluate(x=>{reset();bowl.x=Math.max(715,Math.min(900,x));bowl.y=405},predX);for(let i=0;i<7200;i++){await step();if(await page.evaluate(()=>deposits.length>0||spilled>0))break}tests.ballisticCatch=await page.evaluate(()=>deposits.length>0);await evidence('ballisticCatch','physical trajectory deposit='+tests.ballisticCatch);await shot('09-ballistic-catch-no-attraction');
let before=await page.evaluate(()=>({b:{...bowl},d:deposits.map(x=>centroid(x.points))}));await evidence('bowlCarriesContents','bowl/content starting position','before');if(before.d.length){await page.evaluate(()=>{let old={...bowl};bowl.x+=45;let dx=bowl.x-old.x;for(const d of deposits)for(const p of d.points)p.x+=dx});let after=await page.evaluate(()=>({b:{...bowl},d:deposits.map(x=>centroid(x.points))}));tests.bowlCarriesContents=Math.abs((after.d[0].x-before.d[0].x)-(after.b.x-before.b.x))<1;tests.movedContentsRemainSupported=await page.evaluate(()=>deposits.every(d=>{let c=centroid(d.points),by=bowlY(c.x);return by!==null&&Number.isFinite(c.y)}))}else tests.bowlCarriesContents=false;await evidence('bowlCarriesContents','translation preserved='+tests.bowlCarriesContents,'after');await evidence('movedContentsRemainSupported','supported='+tests.movedContentsRemainSupported);await shot('10-bowl-content-translation');
await page.evaluate(()=>{let Q=q(),old={...bowl},cand={...bowl,x:560,y:400};bowl=cand;if(bowlHeapOverlap(Q))bowl=old});tests.dragCannotEnterHeap=await page.evaluate(()=>!bowlHeapOverlap(q()));await evidence('dragCannotEnterHeap','exclusion after attempted drag='+tests.dragCannotEnterHeap);await shot('11-bowl-heap-exclusion');
for(let i=0;i<3600;i++)await step();let fin=await page.evaluate(()=>({captured,dep:deposits.length,spilled,fall:fall.length,account:(load?1:0)+fall.length+deposits.length+spilled,inv:reality()}));tests.longRunFinite=fin.inv.find(x=>x.n.includes('finite')).ok;tests.iceCreamCohesion=await page.evaluate(()=>!load||polyArea(load.contour)>700);tests.iceCreamNoRigidTeleport=await page.evaluate(()=>fall.every(f=>Number.isFinite(f.vx)&&Number.isFinite(f.vy)));tests.iceCreamGravityResponse=fin.inv.find(x=>x.n.includes('gravity')).ok;tests.iceCreamMassConservation=fin.inv.find(x=>x.n.includes('matter conserved')).ok;tests.iceCreamContactTransfer=fin.inv.find(x=>x.n.includes('capture requires contact')).ok;tests.iceCreamMeltPassive=await page.evaluate(()=>{let Q=q();return Q.m>=0&&Q.m<=1&&fall.every(f=>Number.isFinite(f.vx)&&Number.isFinite(f.vy))});tests.iceCreamNoSolidPenetration=fin.inv.find(x=>x.n.includes('solid bowl excludes heap')).ok;tests.longRunMass=fin.captured===fin.account;tests.noRealityViolation=fin.inv.every(x=>x.ok);tests.noPlaceholderRealityGates=fin.inv.filter(x=>['K08 no bowl attraction','K09 no landing slots','K10 release continuity'].includes(x.n)).every(x=>typeof x.ok==='boolean'&&x.ok);tests.depositSupportNoCoincidence=await page.evaluate(()=>{let cs=deposits.map(d=>centroid(d.points));for(let i=0;i<cs.length;i++)for(let j=i+1;j<cs.length;j++)if(Math.hypot(cs[i].x-cs[j].x,cs[i].y-cs[j].y)<8)return false;return true});for(const name of ['longRunFinite','iceCreamCohesion','iceCreamNoRigidTeleport','iceCreamGravityResponse','iceCreamMassConservation','iceCreamContactTransfer','iceCreamMeltPassive','iceCreamNoSolidPenetration','longRunMass','noRealityViolation','noPlaceholderRealityGates','depositSupportNoCoincidence'])await evidence(name,'long-run observed result='+tests[name]);await shot('12-long-run-reality-state');
for(const name of Object.keys(tests)){if(!evidenceMap[name])await evidence(name,'result='+tests[name]);}
const hashes=shots.map(n=>crypto.createHash('sha256').update(fs.readFileSync(`${out}/${n}`)).digest('hex'));tests.evidenceFramesDistinct=new Set(hashes).size>=9;const report={version:'v1.9',evidenceMap,evidenceComplete:Object.keys(tests).every(k=>!!evidenceMap[k])&&Object.keys(evidenceMap).length===Object.keys(tests).length,validation:'knowledge-derived reality + visual evidence',errors,shots,tests,first,miss,ballistic,predictedCatchX:predX,final:fin,pass:errors.length===0&&Object.values(tests).every(Boolean)&&Object.keys(tests).every(k=>!!evidenceMap[k])};fs.writeFileSync(out+'/TEST-REPORT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await page.context().browser().close();if(!report.pass)process.exit(1);
// v1.6 rerun marker: physical-offset release validation
